TrashVersionOne/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TrashVersionOne.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();
        public virtual void AddItem(ProductDetails product, int quantity)
        {
            CartLine line = lineCollection
            .Where(p => p.Product.Id == product.Id)
            .FirstOrDefault();
            if (line == null)
            {
                lineCollection.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(ProductDetails product) =>
        lineCollection.RemoveAll(l => l.Product.Id == product.Id);
        public virtual decimal ComputeTotalValue() =>
        lineCollection.Sum(e => e.Product.Amount * e.Quantity);
        public virtual void Clear() => lineCollection.Clear();
        public virtual IEnumerable<CartLine> Lines => lineCollection;
    }

      public class CartLine
    {
        public int CartLineID { get; set; }
        public ProductDetails Product { get; set; }
        public int Quantity { get; set; }
    }
}

TrashVersionOne/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrashVersionOne.Infrastructure;
using TrashVersionOne.Models;
using TrashVersionOne.Models.ViewModel;

namespace TrashVersionOne.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;
     

        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
           
        }

        public ViewResult Index(string retunrUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = retunrUrl
            });
        }
       
        public RedirectToActionResult AddToCart(int id, string returnUrl)
        {
            ProductDetails product = repository.Products
            .FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                Cart cart = GetCart();
                cart.AddItem(product, 1);
                SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId,
        string returnUrl)
        {
            ProductDetails product = repository.Products
            .FirstOrDefault(p => p.Id == productId);
            if (product != null)
            {
                Cart cart = GetCart();
                cart.RemoveLine(product);
                SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        private Cart GetCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
            return cart;
        }

        private void SaveCart(Cart cart)
        {
            HttpContext.Session.SetJson("Cart", cart);
        }
    }
}

TrashVersionOne/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrashVersionOne.Models;

namespace TrashVersionOne.Controllers
{
    public class OrdersController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        public OrdersController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }


        public ViewResult List() =>
             View(repository.Orders.Where(o => !o.Shipped));

        [HttpPost]
        public IActionResult MarkShipped(int orderID)
        {
            Order order = repository.Orders
            .FirstOrDefault(o => o.OrderID == orderID);
            if (order != null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }
        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

TrashVersionOne/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrashVersionOne.Models;
using TrashVersionOne.Models.ViewModel;

namespace TrashVersionOne.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 6;

        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int productPage = 1)
            => View(new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Product_category == category)
                .OrderBy(p => p.Id)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    repository.Products.Count() :
                    repository.Products.Where(e => e.Product_category == category).Count()
                },
                CurrentCategory = category
            });

        public ViewResult Details(int Id)
        {
            var product = repository.Products.FirstOrDefault(d => d.Id == Id);
            if (product == null)
            {
                return View("");
            }
            return View(product);
        }
    }
}

TrashVersionOne/Views/Cart/Index.cshtml
@model CartIndexViewModel





<div class="center" style="width:80%; margin-top:80px;">
    <h2 style="color:white">Your cart</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr style="border-color:black">
                <th style="background-color: black; border-color: black; color:white;">Quantity</th>
                <th style="background-color: black; border-color: black; color:white;">Item</th>
                <th style="background-color: black; border-color: black; color:white;" class="text-right">Price</th>
                <th style="background-color: black; border-color: black; color:white;" class="text-right">Subtotal</th>
                <th style="background-color: black; border-color: black; color:white;" class="text-right"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart.Lines)
            {
                <tr>
                    <td style="background-color: white; border-color: white; color:black;" class="text-center">@line.Quantity</td>
                    <td style="background-color: white; border-color: white; color:black;" class="text-left">@line.Product.Product_Name</td>
                    <td style="background-color: white; border-color: white; color:black;" class="text-right">@line.Product.Amount.ToString("c")</td>
                    <td style="background-color: white; border-color: white; color:black;" class="text-right">
                        @((line.Quantity * line.Product.Amount).ToString("c"))
                    </td>
                    <td style="background-color: white; border-color: white; color:black;">
                        <form asp-action="RemoveFromCart" method="post">
                            <input type="hidden" name="ProductID"
                                   value="@line.Product.Id" />
                            <input type="hidden" name="returnUrl"
                                   value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger"
                                    style=" width: 135px; height: 30px; margin-top: -10px; border-radius: 0px; border: none;
                       background: red; color:white; padding-top: 5px; box-shadow: 2px 2px 6px -1px rgba(0,0,0,0.8);">
                                Remove
                            </button>
                        </form>
                    </td>

                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td style="background-color: white; border-color: white; color:black;" colspan="3" class="text-right">Total:</td>
                <td style="background-color: white; border-color: white; color:black;" class="text-right">
                    @Model.Cart.ComputeTotalValue().ToString("c")
                </td>
                <td style="background-color: white; border-color: white; color:black;" colspan="3" class="text-right"></td>
            </tr>
        </tfoot>
    </table><br />
</div>
<div class="text-center">
    <a class="btn btn-primary" asp-action="List" asp-controller="Product"
       style=" width: 150px; height: 30px; margin-top: -10px; border-radius: 0px; border: none;
            background: green; color:white; padding-top: 5px; box-shadow: 2px 2px 6px -1px rgba(0,0,0,0.8);">
        Continue shopping
    </a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Orders"
       style=" width: 150px; height: 30px; margin-top: -10px; border-radius: 0px; border: none;
             background: blue; color:white; padding-top: 5px; box-shadow: 2px 2px 6px -1px rgba(0,0,0,0.8);">
        Checkout
    </a>
</div>