TrashVersionOne/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrashVersionOne.Models;
using TrashVersionOne.Models.ViewModel;

namespace TrashVersionOne.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 6;

        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string category, int productPage = 1)
            => View(new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Product_category == category)
                .OrderBy(p => p.Id)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    repository.Products.Count() :
                    repository.Products.Where(e => e.Product_category == category).Count()
                },
                CurrentCategory = category
            });

        public ViewResult Details(int Id)
        {
            var product = repository.Products.FirstOrDefault(d => d.Id == Id);
            if (product == null)
            {
                return View("");
            }
            return View(product);
        }
    }
}

TrashVersionOne/Views/Shared/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrashVersionOne.Models;

namespace TrashVersionOne.Views.Shared
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}
    

TrashVersionOne/Views/Shared/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrashVersionOne.Models;

namespace TrashVersionOne.Views.Shared
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            return View(repository.Products
                .Select(x => x.Product_category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}
    

TrashVersionOne/Views/Shared/ProductSummary.cshtml
@model ProductDetails
@*<br /><br /><br />*@

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
@*<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>*@
<link href="~/css/Summary.css" rel="stylesheet" />
<script src="~/js/site.js"></script>

<div class="card-columns view-group" style="margin-top: 70px;">
    <div class="item col-xs-12 col-lg-4">
        <div class="thumbnail card" style="min-height:350px">
            <div class="image" style="margin-bottom:30px">
                <a asp-controller="Product" asp-action="Details" asp-route-Id="@Model.Id">
                    <img class="group list-group-image img-fluid" src="@Model.ProductPicture" style="min-height:300px" asp-append-version="true" />
                </a>
                <h5 class="card-title">
                    <a asp-controller="Product" asp-action="Details" asp-route-Id="@Model.Id">
                        @Model.Product_Name
                    </a>
                    <span class="" style="float:right">
                        <big><strong>@Model.Amount.ToString("c")</strong></big>
                    </span>
                </h5>
                <div class="caption" style="border-top:3px solid #808080; ">
                    <p style="word-wrap: break-word; " class="card-text"> @Model.Product_Description.</p>
                    <form id="@Model.Id" asp-action="AddToCart"
                          asp-controller="Cart" method="post">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" name="returnUrl"
                               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit"
                                class="btn btn-success btn-sm pull-right" style="float:right">
                            Add To Cart
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

TrashVersionOne/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/TrashSite.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js">
    </script>
</head>
<body class="m-1 p-1">

    <div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

TrashVersionOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReasureTrash</title>
    <link href="~/css/Style.css" rel="stylesheet" />
    @*<link href="~/css/site.css" rel="stylesheet" />*@
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TrashVersionOne</a>
            </div>
            <div style="margin:auto; width:700px"> 
                <div class="navbar-collapse collapse text-center">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Product" asp-action="List">Shop</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Check">Profile</a></li>
                    <li><img style="width: 50px" src="~/images/1.4-logo.png" /></li>

                    <li>
                        @await Component.InvokeAsync("CartSummary")
                    </li>

                </ul>
                <div style="float:right">  <partial name="_LoginPartial" /> </div> 
            </div>
            </div>
            
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    


    <div class="container body-content">

        

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - TrashVersionOne</p>
        </footer>
    </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
</body>
</html>